Update blank.yml
Signed-off-by: Niels <145555177+nttniels@users.noreply.github.com>

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -15,25 +15,12 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  check_branche:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
-
-      # Runs a set of commands using the runners shell
-      - name: Branche check
+      - name: Check branche
+        if: github.base_ref == '10-production' && github.head_ref != '20-quality'
         run: |
-          ALLOWED_BRANCH="20-quality"
-          if [[ $GIT_REFLOG_ACTION == *merge* ]]; then
-          	if [[ $GIT_REFLOG_ACTION == *$ALLOWED_BRANCH* ]]; then
-          		echo \# Merge from 20-quality is allowed
-          		exit 0
-          	fi
-             echo \# Only allowed to merge from 20-quality.
-             exit 1
-          fi
+          echo "ERROR: You can only merge to 10-production from 20-quality."
+          exit 1
